import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        width: '100%',
        height: '100%',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(30, 39, 46, 0.7)',
        borderRadius: 10,
        padding: 20,
        margin: 20,
    },
    loadingText: {
        color: '#fff',
        marginTop: 10,
        fontSize: 16,
    },
    forecastContainer: {
        flex: 1,
        padding: 15,
    },
    headerContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 10,
        marginBottom: 10,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255, 255, 255, 0.2)',
    },
    heading: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#fff",
        flex: 1,
    },
    locationText: {
        fontSize: 16,
        color: "#EAECEE",
        flex: 1,
        textAlign: 'center',
    },
    refreshButton: {
        padding: 8,
        borderRadius: 20,
        backgroundColor: 'rgba(135, 206, 235, 0.3)',
    },
    listContainer: {
        paddingBottom: 20,
    },
    dayContainer: {
        backgroundColor: "rgba(52, 73, 94, 0.85)",
        borderRadius: 15,
        marginBottom: 15,
        padding: 15,
        shadowColor: "#000",
        shadowOffset: { width: 3, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 5,
    },
    dayHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255, 255, 255, 0.2)',
        paddingBottom: 10,
        marginBottom: 10,
    },
    dayText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: "#fff",
    },
    dayAvgTemp: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    avgTempText: {
        color: "skyblue",
        fontWeight: 'bold',
        marginLeft: 5,
    },
    weatherIconContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 15,
    },
    weatherCondition: {
        fontSize: 18,
        color: "#fff",
        fontWeight: "bold",
        marginLeft: 10,
    },
    hourlyItemContainer: {
        backgroundColor: "rgba(30, 39, 46, 0.6)",
        borderRadius: 10,
        padding: 12,
        marginRight: 10,
        alignItems: 'center',
        width: 100,
    },
    hourText: {
        fontSize: 14,
        color: "#EAECEE",
        marginBottom: 8,
    },
    temperatureText: {
        fontSize: 18,
        fontWeight: "bold",
        color: "skyblue",
        marginVertical: 6,
    },
    humidityContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    humidityText: {
        fontSize: 14,
        color: "#EAECEE",
        marginLeft: 4,
    },
});