
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: '100%',
    height: '100%',  
  },
  keyboardAvoidView: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  contentContainer: {
    backgroundColor: "rgba(52, 73, 94, 0.85)", 
    padding: 25,
    borderRadius: 15,
    width: "95%",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    marginVertical: 20,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(30, 39, 46, 0.7)', 
    borderRadius: 10,
    padding: 20,
    marginTop: 150,
  },
  loadingText: {
    color: '#fff',
    marginTop: 10,
    fontSize: 16,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#EAECEE",
    marginBottom: 20,
    textAlign: "center",
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: "90%",
    backgroundColor: "white",
    borderRadius: 10,
    paddingHorizontal: 10,
    marginBottom: 15,
    borderColor: "skyblue",
    borderWidth: 2,
  },
  searchIcon: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    padding: 12,
    fontSize: 18,
    color: "#34495E",
  },
  errorText: {
    color: "#ff6b6b",
    marginBottom: 15,
    textAlign: "center",
    fontWeight: "500",
  },
  weatherButton: {
    backgroundColor: "skyblue",
    flexDirection: "row",
    paddingVertical: 14,
    paddingHorizontal: 30,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  weatherButtonText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
    marginLeft: 8,
  },
  resultContainer: {
    width: "100%",
    alignItems: "center",
    backgroundColor: "rgba(30, 39, 46, 0.6)",
    borderRadius: 10,
    padding: 15,
    marginTop: 10,
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  locationText: {
    fontSize: 18,
    color: "#EAECEE",
    marginLeft: 5,
    fontWeight: "500",
  },
  iconContainer: {
    alignItems: 'center',
    marginBottom: 15,
  },
  conditionText: {
    fontSize: 20,
    color: "#fff",
    fontWeight: "bold",
    marginTop: 5,
  },
  detailsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    width: '100%',
  },
  detailItem: {
    width: '48%',
    backgroundColor: "rgba(135, 206, 235, 0.25)",
    padding: 15,
    borderRadius: 10,
    alignItems: "center",
    marginBottom: 10,
  },
  detailLabel: {
    fontSize: 16,
    color: "#EAECEE",
    marginTop: 5,
  },
  detailValue: {
    fontSize: 20,
    color: "skyblue",
    fontWeight: "bold",
    marginTop: 5,
  },
  forecastButton: {
    backgroundColor: "skyblue",  
    flexDirection: "row",
    paddingVertical: 14,
    paddingHorizontal: 30,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 15,
    width: "100%",
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  forecastButtonText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
    marginLeft: 8,
  },
  forecastContainer: {
    width: "100%",
    backgroundColor: "rgba(30, 39, 46, 0.6)",
    borderRadius: 10,
    padding: 15,
    marginTop: 20,
  },
  forecastTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#fff",
    textAlign: "center",
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.2)',
    paddingBottom: 10,
  },
  
  dayContainer: {
    backgroundColor: "rgba(52, 73, 94, 0.85)",
    borderRadius: 15,
    marginBottom: 15,
    padding: 15,
    shadowColor: "#000",
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  dayHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.2)',
    paddingBottom: 10,
    marginBottom: 10,
  },
  dayText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: "#fff",
  },
  dayAvgTemp: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avgTempText: {
    color: "skyblue",
    fontWeight: 'bold',
    marginLeft: 5,
  },
  weatherIconContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 15,
  },
  weatherCondition: {
    fontSize: 18,
    color: "#fff",
    fontWeight: "bold",
    marginLeft: 10,
  }, 
  hourlyForecastHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  hourlyForecastText: {
    fontSize: 14,
    color: '#fff',
    fontWeight: '500',
  },
  scrollIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(30, 39, 46, 0.4)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    elevation: 2,
  },
  scrollText: {
    fontSize: 12,
    color: 'skyblue',
    marginLeft: 2,
  },
  hourlyItemContainer: {
    backgroundColor: "rgba(30, 39, 46, 0.6)",
    borderRadius: 10,
    padding: 12,
    marginRight: 10,
    alignItems: 'center',
    width: 100,
  },
  hourText: {
    fontSize: 14,
    color: "#EAECEE",
    marginBottom: 8,
  },
  temperatureText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "skyblue",
    marginVertical: 6,
  },
  humidityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  humidityText: {
    fontSize: 14,
    color: "#EAECEE",
    marginLeft: 4,
  }
});