import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        width: '100%',
        height: '100%',
    },
    keyboardAvoidView: {
        flex: 1,
    },
    scrollContainer: {
        flexGrow: 1,
        alignItems: "center",
        justifyContent: "center",
        padding: 20,
    },
    contentContainer: { 
        backgroundColor: "rgba(52, 73, 94, 0.85)",  
        padding: 25,
        borderRadius: 15,
        width: "95%",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 3, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 5,
        marginVertical: 20,
    },
    title: {
        fontSize: 28,
        fontWeight: "bold",
        color: "#EAECEE",
        marginBottom: 20,
        textAlign: "center",
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        width: "90%",
        backgroundColor: "white",
        borderRadius: 10,
        paddingHorizontal: 10,
        marginBottom: 15,
        borderColor: "skyblue",
        borderWidth: 2,
    },
    searchIcon: {
        marginRight: 10,
    },
    input: {
        flex: 1,
        padding: 12,
        fontSize: 18,
        color: "#34495E",
    },
    errorText: {
        color: "#ff6b6b",
        marginBottom: 15,
        textAlign: "center",
        fontWeight: "500",
    },
    weatherButton: {
        backgroundColor: "skyblue",
        flexDirection: "row",
        paddingVertical: 14,
        paddingHorizontal: 30,
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 20,
        shadowColor: "#000",
        shadowOffset: { width: 2, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 3,
    },
    weatherButtonText: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#fff",
        marginLeft: 8,
    },
    resultContainer: {
        width: "100%",
        alignItems: "center",
        backgroundColor: "rgba(30, 39, 46, 0.6)",
        borderRadius: 10,
        padding: 15,
        marginTop: 10,
    },
    locationContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 15,
    },
    locationText: {
        fontSize: 18,
        color: "#EAECEE",
        marginLeft: 5,
        fontWeight: "500",
    },
    iconContainer: {
        alignItems: 'center',
        marginBottom: 15,
    },
    conditionText: {
        fontSize: 20,
        color: "#fff",
        fontWeight: "bold",
        marginTop: 5,
    },
    detailsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
    },
    detailItem: {
        width: '48%',
        backgroundColor: "rgba(135, 206, 235, 0.25)",
        padding: 15,
        borderRadius: 10,
        alignItems: "center",
    },
    detailLabel: {
        fontSize: 16,
        color: "#EAECEE",
        marginTop: 5,
    },
    detailValue: {
        fontSize: 20,
        color: "skyblue",
        fontWeight: "bold",
        marginTop: 5,
    },
});